### ISSUE TITLE
USER STORY: As a site user I can chose whether to search items based on price or rating so that my search is more efficient while viewing items.

### ISSUE THREAD

**Issue by DaniCarmo** [DaniCarmo/Florist-p5#1]
EPIC: Search by Price

As a site user I can chose whether to search items based on price or rating so that my search is more efficient while viewing items.

Acceptance Criteria

- [ ] I navigate to any product on the navbar
- [ ] From the dropdown menu I can select price
- [ ] I can view the products by price lowest to highest

Tasks

- [ ] Create a dropdown within the navbar
- [ ] Provide an option to view by price for user to click on
- [ ] This is linked to products page where user can view the selected products in order of price from lowest to highest
