### ISSUE TITLE
USER STORY: As a site user I can chose whether to search items based on rating so that my search is more efficient while viewing items.

### ISSUE THREAD

**Issue by DaniCarmo** [DaniCarmo/Florist-p5#2]
EPIC: Search by Rating

As a site user I can chose whether to search items based on rating so that my search is more efficient while viewing items.

Acceptance Criteria

- [ ] I navigate to any product on the navbar
- [ ] From the dropdown menu I can select rating
- [ ] I can view the products by rating from highest to lowest

Tasks

- [ ] Create a dropdown within the navbar
- [ ] Provide an option to view by rating for user to click on
- [ ] This is linked to products page where user can view the selected products in order of rating from highest to lowest
