### ISSUE TITLE
USER STORY: As a user I want to create an account so I can log in when ordering and receive updates and discounts

### ISSUE THREAD

**Issue by DaniCarmo** [DaniCarmo/Florist-p5#4]
EPIC: Create Account/Login

As a user I want to create an account so I can log in when ordering and receive updates and discounts

Acceptance Criteria

- [ ]  Given that I am a registered user, who is not logged in
- [ ]  When I navigate to the sign in page I enter my credentials correctly and click login
- [ ]  Then I am signed into my account
- [ ]  I also have the option to logout

Tasks

- [ ] Develop the ability for users to sign into their account
- [ ] Develop a sign in form to capture user sign in details
- [ ] Develop form validation to ensure the data is correct
- [ ] Develop a method to validate the data entered matches a user account
- [ ] Develop a link for users to sign out of their account – should be accessible from all pages – suggest within nav bar, user account section
