### ISSUE TITLE
USER STORY: As a Site User I can view a product in more details

### ISSUE THREAD

**Issue by DaniCarmo** [DaniCarmo/Florist-p5#5]
EPIC: View Product Page

As a Site User I can view a product in more details

Acceptance Criteria

- [ ] Given that I am a user on the site
- [ ] When I navigate to the products I can click on a product  to view more details
- [ ] Then I am presented with a product detail page with a product description, sizes available and prices

Tasks

- [ ] Develop a link all users can access to the products page
- [ ] The products page should list all of the related products in product cards
- [ ] Create a link from the card to the full product details page
- [ ] Develop a product details page that provides the full details with a product description, sizes available and prices
