### ISSUE TITLE
USER STORY: As a site user I will receive order confirmation after checkout

### ISSUE THREAD

**Issue by DaniCarmo** [DaniCarmo/Florist-p5#9]
EPIC: Order Confirmation

As a site user I will receive order confirmation after checkout so that I can review my order to ensure everything is correct and have a receipt

Acceptance Criteria

- [ ] Given that I am a user on the site and added items to bt cart
- [ ] I complete checkout and brought to a order confirmation page
- [ ] I receive a confirmation email to my provided email at checkout, with order details

- [ ] Create order confirmation/checkout success page
- [ ] When users complete checkout successfully they are brought to another page confirming their order
- [ ] User also reveives an email; set up confirmation email
